/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const City = IDL.Record({ 'country' : IDL.Text, 'name' : IDL.Text });
export const Preferences = IDL.Record({ 'city' : IDL.Text, 'unit' : IDL.Text });

export const idlService = IDL.Service({
  'getCities' : IDL.Func([], [IDL.Vec(City)], ['query']),
  'getPreferences' : IDL.Func([IDL.Text], [IDL.Opt(Preferences)], ['query']),
  'savePreferences' : IDL.Func([IDL.Text, Preferences], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const City = IDL.Record({ 'country' : IDL.Text, 'name' : IDL.Text });
  const Preferences = IDL.Record({ 'city' : IDL.Text, 'unit' : IDL.Text });
  
  return IDL.Service({
    'getCities' : IDL.Func([], [IDL.Vec(City)], ['query']),
    'getPreferences' : IDL.Func([IDL.Text], [IDL.Opt(Preferences)], ['query']),
    'savePreferences' : IDL.Func([IDL.Text, Preferences], [], []),
  });
};

export const init = ({ IDL }) => { return []; };